apiVersion: v1
kind: ConfigMap
metadata:
  name: db-secret-credentials
  labels:
    app: postgresdb
data:
  POSTGRES_DB: "postgres"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "mysecretpassword"
  HOST: "postgresdb.default"
  PORT: "5432"
  DATABASE_URL: "postgres://postgres:mysecretpassword@localhost/postgres"
